baseURL = "https://josepeck.github.io/dubaichocolatemadrid/"
languageCode = 'en-us'
title = 'Dubai Chocolate'
theme = 'ananke'
publishDir = "docs"

# Optional configurations:
[params]
  description = "Finest Chocolates from Dubai"
  show_reading_time = false